server:
  port: 8084

spring:
  zipkin:
    enabled: true
    baseUrl: http://zipkin:9411
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq
    port: 5672

queue:
  movie:
    name: Movie
  serie:
    name: Serie

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka

resilience4j:
  retry:
    instances:
      movie:
        maxAttempts: 3
        waitDuration: 1000
        retryException[0]: feign.feignException$InternalServerError
  circuitbreaker:
    instances:
      movie:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: true

management:
  health:
    circuitbreakers:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Catalog Microservice
