ports:
  - 3306:3306

environment:
  - MYSQL_DATABASE=backend-Final
  - MYSQL_USER=user
  - MYSQL_PASSWORD=pass
  - MYSQL_ROOT_PASSWORD=pass

mongodb:
  image: mongo
  container_name: "mongodb"
  command: mongod --auth
  environment:
    - MONGO_INITDB_DATABASE=admin
    - MONGO_INITDB_ROOT_USERNAME=rootuser
    - MONGO_INITDB_ROOT_PASSWORD=rootpass
  ports:
    - "27017:27017"

config-service:
  image: config-service
  ports:
    - "8888:8888"
  restart: always

movie-service:
  image: movie-service
  ports:
    - "8082:8082"
  restart: always

eureka-service:
  image: eureka-service
  ports:
    - "8761:8761"
  restart: always

serie-service:
  image: serie-service
  ports:
    - "8095:8095"
  restart: always

api-gateway:
  image: api-gateway
  ports:
    - "8080:8080"
  restart: always

catalog-service:
  image: catalog-service
  ports:
    - "8084:8084"
  restart: always
